/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ZerniolinksRouteImport } from './routes/zerniolinks'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedListadoRouteImport } from './routes/_authenticated/listado'
import { Route as AuthenticatedPublicacionesRouteImport } from './routes/_authenticated/publicaciones'
import { Route as AuthenticatedSubirRouteImport } from './routes/_authenticated/subir'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AuthenticatedAjustesIndexRouteImport } from './routes/_authenticated/ajustes/index'
import { Route as AuthenticatedAjustesCredencialesRouteImport } from './routes/_authenticated/ajustes/credenciales'
import { Route as AuthenticatedAjustesUsuariosRouteImport } from './routes/_authenticated/ajustes/usuarios'
import { Route as ApiPublicR2DownloadUrlRouteImport } from './routes/api/public/r2-download-url'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ZerniolinksRoute = ZerniolinksRouteImport.update({
  id: '/zerniolinks',
  path: '/zerniolinks',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedListadoRoute = AuthenticatedListadoRouteImport.update({
  id: '/listado',
  path: '/listado',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPublicacionesRoute =
  AuthenticatedPublicacionesRouteImport.update({
    id: '/publicaciones',
    path: '/publicaciones',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSubirRoute = AuthenticatedSubirRouteImport.update({
  id: '/subir',
  path: '/subir',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAjustesIndexRoute =
  AuthenticatedAjustesIndexRouteImport.update({
    id: '/ajustes/',
    path: '/ajustes/',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAjustesCredencialesRoute =
  AuthenticatedAjustesCredencialesRouteImport.update({
    id: '/ajustes/credenciales',
    path: '/ajustes/credenciales',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAjustesUsuariosRoute =
  AuthenticatedAjustesUsuariosRouteImport.update({
    id: '/ajustes/usuarios',
    path: '/ajustes/usuarios',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const ApiPublicR2DownloadUrlRoute = ApiPublicR2DownloadUrlRouteImport.update({
  id: '/api/public/r2-download-url',
  path: '/api/public/r2-download-url',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/login': typeof LoginRoute
  '/zerniolinks': typeof ZerniolinksRoute
  '/listado': typeof AuthenticatedListadoRoute
  '/publicaciones': typeof AuthenticatedPublicacionesRoute
  '/subir': typeof AuthenticatedSubirRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/ajustes/credenciales': typeof AuthenticatedAjustesCredencialesRoute
  '/ajustes/usuarios': typeof AuthenticatedAjustesUsuariosRoute
  '/api/public/r2-download-url': typeof ApiPublicR2DownloadUrlRoute
  '/ajustes/': typeof AuthenticatedAjustesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/zerniolinks': typeof ZerniolinksRoute
  '/listado': typeof AuthenticatedListadoRoute
  '/publicaciones': typeof AuthenticatedPublicacionesRoute
  '/subir': typeof AuthenticatedSubirRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AuthenticatedIndexRoute
  '/ajustes/credenciales': typeof AuthenticatedAjustesCredencialesRoute
  '/ajustes/usuarios': typeof AuthenticatedAjustesUsuariosRoute
  '/api/public/r2-download-url': typeof ApiPublicR2DownloadUrlRoute
  '/ajustes': typeof AuthenticatedAjustesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/zerniolinks': typeof ZerniolinksRoute
  '/_authenticated/listado': typeof AuthenticatedListadoRoute
  '/_authenticated/publicaciones': typeof AuthenticatedPublicacionesRoute
  '/_authenticated/subir': typeof AuthenticatedSubirRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/ajustes/credenciales': typeof AuthenticatedAjustesCredencialesRoute
  '/_authenticated/ajustes/usuarios': typeof AuthenticatedAjustesUsuariosRoute
  '/api/public/r2-download-url': typeof ApiPublicR2DownloadUrlRoute
  '/_authenticated/ajustes/': typeof AuthenticatedAjustesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/zerniolinks'
    | '/listado'
    | '/publicaciones'
    | '/subir'
    | '/auth/callback'
    | '/ajustes/credenciales'
    | '/ajustes/usuarios'
    | '/api/public/r2-download-url'
    | '/ajustes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/zerniolinks'
    | '/listado'
    | '/publicaciones'
    | '/subir'
    | '/auth/callback'
    | '/'
    | '/ajustes/credenciales'
    | '/ajustes/usuarios'
    | '/api/public/r2-download-url'
    | '/ajustes'
  id:
    | '__root__'
    | '/_authenticated'
    | '/login'
    | '/zerniolinks'
    | '/_authenticated/listado'
    | '/_authenticated/publicaciones'
    | '/_authenticated/subir'
    | '/auth/callback'
    | '/_authenticated/'
    | '/_authenticated/ajustes/credenciales'
    | '/_authenticated/ajustes/usuarios'
    | '/api/public/r2-download-url'
    | '/_authenticated/ajustes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  ZerniolinksRoute: typeof ZerniolinksRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ApiPublicR2DownloadUrlRoute: typeof ApiPublicR2DownloadUrlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/zerniolinks': {
      id: '/zerniolinks'
      path: '/zerniolinks'
      fullPath: '/zerniolinks'
      preLoaderRoute: typeof ZerniolinksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/listado': {
      id: '/_authenticated/listado'
      path: '/listado'
      fullPath: '/listado'
      preLoaderRoute: typeof AuthenticatedListadoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/publicaciones': {
      id: '/_authenticated/publicaciones'
      path: '/publicaciones'
      fullPath: '/publicaciones'
      preLoaderRoute: typeof AuthenticatedPublicacionesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/subir': {
      id: '/_authenticated/subir'
      path: '/subir'
      fullPath: '/subir'
      preLoaderRoute: typeof AuthenticatedSubirRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/ajustes/': {
      id: '/_authenticated/ajustes/'
      path: '/ajustes'
      fullPath: '/ajustes/'
      preLoaderRoute: typeof AuthenticatedAjustesIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes/credenciales': {
      id: '/_authenticated/ajustes/credenciales'
      path: '/ajustes/credenciales'
      fullPath: '/ajustes/credenciales'
      preLoaderRoute: typeof AuthenticatedAjustesCredencialesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ajustes/usuarios': {
      id: '/_authenticated/ajustes/usuarios'
      path: '/ajustes/usuarios'
      fullPath: '/ajustes/usuarios'
      preLoaderRoute: typeof AuthenticatedAjustesUsuariosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/r2-download-url': {
      id: '/api/public/r2-download-url'
      path: '/api/public/r2-download-url'
      fullPath: '/api/public/r2-download-url'
      preLoaderRoute: typeof ApiPublicR2DownloadUrlRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedListadoRoute: typeof AuthenticatedListadoRoute
  AuthenticatedPublicacionesRoute: typeof AuthenticatedPublicacionesRoute
  AuthenticatedSubirRoute: typeof AuthenticatedSubirRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedAjustesCredencialesRoute: typeof AuthenticatedAjustesCredencialesRoute
  AuthenticatedAjustesUsuariosRoute: typeof AuthenticatedAjustesUsuariosRoute
  AuthenticatedAjustesIndexRoute: typeof AuthenticatedAjustesIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedListadoRoute: AuthenticatedListadoRoute,
  AuthenticatedPublicacionesRoute: AuthenticatedPublicacionesRoute,
  AuthenticatedSubirRoute: AuthenticatedSubirRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedAjustesCredencialesRoute: AuthenticatedAjustesCredencialesRoute,
  AuthenticatedAjustesUsuariosRoute: AuthenticatedAjustesUsuariosRoute,
  AuthenticatedAjustesIndexRoute: AuthenticatedAjustesIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  ZerniolinksRoute: ZerniolinksRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ApiPublicR2DownloadUrlRoute: ApiPublicR2DownloadUrlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
